-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- monitor = DP-1, 3440x1440@160, 1920x0, auto
-- monitor = DP-2, 1920x1080@240, 0x220, auto
-- monitor = DP-1, 3440x1440@160, 1080x200, auto
-- monitor = DP-2, 1920x1080@240, 0x0, auto, transform, 1

--## MAIN
hl.workspace_rule({
    workspace = "1",
    monitor = "DP-1",
    default = true,
})

hl.workspace_rule({
    workspace = "6",
    monitor = "DP-2",
    default = true,
})

hl.workspace_rule({
    workspace = "10",
    monitor = "HDMI-A-1",
    default = true,
})

-- monitor = HDMI-A-1, 3840x2160@60,5360x0,auto
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@120",
    position = "0x0",
    scale = "auto",
})

hl.monitor({
    output = "DP-1",
    mode = "3440x1440@160",
    position = "1920x0",
    scale = "auto",
})

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@240",
    position = "5360x0",
    scale = "auto",
})

--## MULTI MONITOR DISABLED FOR CHEATING SECURITY

--monitor = HDMI-A-1, 1920x1080@120, 0x0, auto
--monitor = DP-1, 3440x1440@160, 1920x0, auto
--monitor = DP-2, 1920x1080@240, 0x0, auto

hl.layer_rule({
    name = "noctalia",
    match = {
        namespace = "noctalia-background-.*$",
    },
    ignore_alpha = 0.5,
    blur = true,
    blur_popups = true,
})

local ipc = "noctalia msg"
local terminal = "kitty"
local fileManager = "nemo"

hl.bind("SUPER + SPACE", hl.dsp.exec_cmd(ipc .. " panel-toggle launcher"))
hl.bind("SUPER + S", hl.dsp.exec_cmd(ipc .. " controlCenter toggle"))
hl.bind("SUPER + comma", hl.dsp.exec_cmd(ipc .. " settings toggle"))

hl.bind("SUPER + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + E", hl.dsp.exec_cmd(fileManager))
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + B", hl.dsp.exec_cmd("helium-browser"))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())
hl.bind("SUPER + J", hl.dsp.layout("togglesplit"))
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("Print", hl.dsp.exec_cmd("filename=~/Pictures/Screenshots/$(date +'%d-%m-%Y_%Hh-%Mm-%Ss').png && grim -g \"$(slurp)\" \"$filename\" && wl-copy < \"$filename\""))

hl.bind("CTRL + SHIFT + L", hl.dsp.exec_cmd("/home/luigr/Documents/scripts/toggle-mic.sh"))
hl.bind("CTRL + SHIFT + O", hl.dsp.exec_cmd("/home/luigr/Documents/scripts/cycle-output.sh"))
hl.bind("CTRL + SHIFT + K", hl.dsp.exec_cmd("/home/luigr/Documents/scripts/shutdown-timer.sh"))
hl.bind("CTRL + SHIFT + U", hl.dsp.exec_cmd("/home/luigr/Documents/scripts/cancel-shutdown.sh"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(ipc .. " volume increase"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(ipc .. " volume decrease"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(ipc .. " volume muteOutput"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(ipc .. " brightness increase"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(ipc .. " brightness decrease"), { locked = true, repeating = true })

hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.env("XCURSOR_THEME", "macos-tahoe-cursor")
hl.env("XCURSOR_SIZE", "24")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("HYPRLAND_LOG_WLR", "1")
hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")

hl.window_rule({
    match = {
        class = "Matplotlib",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "awakened-poe-trade",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "scalpel",
    },
    no_blur = true,
    no_anim = true,
})

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
    },
    decoration = {
        rounding = 20,
        rounding_power = 2,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 2,
            vibrancy = 0.1696,
        },
    },
    -- Core binds
    -- Media keys
    input = {
        follow_mouse = 1,
        sensitivity = 0,
        accel_profile = "flat",
        touchpad = {
            natural_scroll = false,
        },
        kb_layout = "us",
        kb_variant = "altgr-intl",
    },
    dwindle = {
        preserve_split = true,
    },
    --windowrule = match:class awakened-poe-trade, noblur on
    --windowrule = match:class awakened-poe-trade, noborder on
    --windowrule = match:class steam_app_2694490, float on
    --windowrule = match:class steam_app_2694490, fullscreen on
})

hl.on("hyprland.start", function()
    hl.exec_cmd("noctalia")
    hl.exec_cmd("hyprctl setcursor macos-tahoe-cursor 24")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("/home/luigr/Documents/startup/Nextcloud-34.0.3-x86_64.AppImage")
    hl.exec_cmd("flatpak run org.keepassxc.KeePassXC")
end)

